#!/usr/bin/env node
/* ================================================================
   VENDOR-FONTS.MJS — Bring the typefaces in-house

   The site used to load Nunito and Space Mono from
   fonts.googleapis.com. That sat badly beside its own README, which
   says there is "no CDN for the JavaScript — a supply chain I do not
   control": a stylesheet from a third party is the same supply
   chain, and it is one that also gets told, before a word of the
   page has rendered, the IP address and referring page of every
   person who visits.

   So this fetches the CSS Google would serve, downloads the .woff2
   files it points at, and rewrites the @font-face rules to local
   paths. Two origins then leave the content security policy
   entirely, the site makes no third-party requests at all, and the
   fonts keep working offline.

   Latin subsets only. This is an English-language CV; the Cyrillic,
   Greek and Vietnamese ranges Google ships would be dead weight on
   every load.

     node tools/vendor-fonts.mjs

   Re-run it to pick up upstream font revisions. It is deliberately a
   manual step, not a build: the output is committed, and the site
   still has no build pipeline.
================================================================ */

import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const FONT_DIR = join(ROOT, 'assets', 'fonts');

/* Google serves different files depending on the User-Agent. A modern
   one gets woff2, which is what every browser this site supports
   understands and is roughly half the size of woff. */
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 '
  + '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const SOURCE = 'https://fonts.googleapis.com/css2'
  + '?family=Nunito:wght@400;600;700;800'
  + '&family=Space+Mono:wght@400;700'
  + '&display=swap';

const KEEP = new Set(['latin', 'latin-ext']);

const curl = (args) => execFileSync('curl', ['-sS', '--fail', '-A', UA, ...args]);

const css = curl([SOURCE]).toString();
const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[\s\S]*?\})/g)];
if (!blocks.length) {
  console.error('No @font-face blocks came back — the upstream format changed.');
  process.exit(1);
}

rmSync(FONT_DIR, { recursive: true, force: true });
mkdirSync(FONT_DIR, { recursive: true });

const downloaded = new Map();   // remote url -> local filename
const rules = [];

for (const [, subset, block] of blocks) {
  if (!KEEP.has(subset)) continue;

  const family = /font-family:\s*'([^']+)'/.exec(block)[1];
  const weight = /font-weight:\s*(\d+)/.exec(block)[1];
  const url = /src:\s*url\(([^)]+)\)/.exec(block)[1];

  if (!downloaded.has(url)) {
    /* Several weights of a variable family share one file. Name it for
       what it is rather than for whichever weight happened to be
       declared first, or the next reader wonders why 800 is being
       served from a file called 400. */
    const shared = blocks.filter(([, s, b]) => KEEP.has(s) && b.includes(url)).length > 1;
    const slug = family.toLowerCase().replace(/\s+/g, '-');
    const name = `${slug}-${shared ? 'var' : weight}-${subset}.woff2`;
    curl(['-o', join(FONT_DIR, name), url]);
    downloaded.set(url, name);
  }

  rules.push(`/* ${family} ${weight} — ${subset} */\n`
    + block.replace(`url(${url})`, `url('../assets/fonts/${downloaded.get(url)}')`));
}

const header = `/* ================================================================
   FONTS.CSS — Self-hosted typefaces

   GENERATED by tools/vendor-fonts.mjs. Do not edit by hand; re-run
   the script instead.

   These used to come from fonts.googleapis.com. They are served from
   this origin now so that the site depends on no third party, tells
   no third party who is reading it, and keeps its typography
   offline. Latin subsets only.

   Source: ${SOURCE}
   Vendored: ${new Date().toISOString().slice(0, 10)}
================================================================ */

`;

writeFileSync(join(ROOT, 'css', 'fonts.css'), header + rules.join('\n\n') + '\n');

console.log(`${downloaded.size} font files, ${rules.length} @font-face rules`);
for (const name of downloaded.values()) console.log(`  assets/fonts/${name}`);
